name: heatwaves
channels:
- conda-forge
# - defaults
dependencies:
- pip
- python
# data fetch
- cdsapi
# visualisation
- matplotlib

# data analysis
- netCDF4
- joblib
# - python-cdo # pip install cdo
# - cdo # avoidable if possible
# Service client
- jupyterlab
- birdy
- scipy
- scikit-learn
# - pywps>=4.5.1,<4.6
# - jinja2
# - click
# - psutil
# tests
# - pytest
